---
title: "ACPf_propre"
format: html
---

```{r library}
library(tidyverse)
library(dplyr)
library(fda)
library(viridis)
```


```{r data}
meteo_lm <- read.csv("data/meteo_lm")
summary(meteo_lm)
glimpse(meteo_lm)

ref_lm <- read.csv("data/ref_lm.csv")
ref_lm_v <- ref_lm$x[2:7]
periode_clim <- ref_lm$X[2:7] 
periode_clim <- sub("_s$", "", periode_clim)

rendement <- read.csv("data/rendement.csv") |>
  dplyr::select(-X) |> 
  dplyr::mutate(variety = sub("^[^_]*_[^_]*_", "", variety))

meteo_brute <- read.csv("data/meteo_brute.csv")
lm <- read.csv("data/landmarks.csv") |> 
  mutate(DEBUT_EXP_sn = as.numeric(as.Date(DEBUT_EXP_s)),
         DEBUT_CW_sn = as.numeric(as.Date(DEBUT_CW_s)),
         FIN_CW_sn = as.numeric(as.Date(FIN_CW_s)),
         DEBUT_FLO_sn = as.numeric(as.Date(DEBUT_FLO_s)),
         FIN_FLO_sn = as.numeric(as.Date(FIN_FLO_s)),
         FIN_EXP_sn = as.numeric(as.Date(FIN_EXP_s)),
         DEBUT_FLO_sn = as.numeric(as.Date(DEBUT_FLO_s)))

```


```{r noms}
noms <- c("INRA11","BGA11",
          "INRA12",
          "INRA13","TI13",
          "EUR14","SYN14","MAD14","RAGT14",
          "TI15","LIM15","SYN15","INRA15","BGA15","RAGT15","MAD15",
          "INRA16",
          "INRA17",
          "INRA18","EUR18")
```


```{r fonction crea data pour acp f}

data_acp_f <- function(var, centre = FALSE, plot = TRUE, nbspines = 30){
  rangeval <- c(min(meteo_lm$date_ref), max(meteo_lm$date_ref)) # définition de l'échelle (les longueurs d'ondes)
  nbasis <- nbspines # Nombre de splines utilisées
  basisobj <- create.bspline.basis(rangeval = rangeval, nbasis = nbasis) # création d'une base d'objet
  
  
  data_var <- meteo_lm |> 
    dplyr::select(exp, date_ref, {{var}}) |> 
    mutate(date_ref = as.numeric(date_ref)) |> 
    pivot_wider(names_from = date_ref, values_from = {{var}}) |> 
    column_to_rownames("exp") 
  
  
  ##### si on veut faire une acp et non une svd 
  if(centre){
    m <- apply(data_var, 1, mean)
    s <- apply(data_var - m, 1, sd)
    
    data_var <- (data_var - m) / s |> 
      as.matrix() 
  }
  
  data_var <- as.matrix(data_var) 
  
  time <- as.numeric(colnames(data_var))
  fdParobj <- fdPar(basisobj, lambda = 1e-3)
  
  fdsmooth <- smooth.basis(
    argvals  = time,
    y        = t(data_var),  # smooth.basis attend temps × individus
    fdParobj = fdParobj
  )
  
  
  fdobj <- fdsmooth$fd
  
  if(plot){plot(fdobj)}
  
  return(fdobj)
}

fdobj <- data_acp_f(E.HYD_WSC, centre = F, plot = T)

```


```{r plot_harmonique}

plot_harmonique <- function(acpf, i, variable){
  fd_eval <- eval.fd(seq(11219, 11502, length.out = 100), acpf$harmonics[i])
  
  ylim <- range(fd_eval)
  num <- c("Première", "Deuxième", "Troisième", "Quatrième", "Cinquième")
  saison <- c("AUTOMNE", "HIVER", "MONTAISON", "FLORAISON", "P300-P1000")
  
  plot(acpf$harmonics[i],
       main = paste(num[i], "composante principale fonctionnelle"),
       xlab = "",
       xaxt = "n",
       ylab = paste("Valeur de la", num[i], "composante principale"))
  
  cols <- adjustcolor(
    c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#F15854"),
    alpha.f = 0.25)
  
  rect(ref_lm_v[-length(ref_lm_v)],  # xleft
       ylim[1],                # ybottom
       ref_lm_v[-1],               # xright
       ylim[2],                # ytop
       col = cols,
       border = NA)
  
  y_text <- ylim[1] + 0.05 * diff(ylim)
  
  x_centers <- (ref_lm_v[-length(ref_lm_v)] + ref_lm_v[-1]) / 2  # centre des rectangles
  y_label <- ylim[1] - 0.1 * diff(ylim)                         # un peu en dessous
  text(x = x_centers[1:length(saison)], 
       y = y_label, 
       labels = saison, 
       cex = 0.9, 
       xpd = TRUE)
  
}

#plot_harmonique(acpf, 1)  #humidité moyenne
#plot_harmonique(acpf, 2)  #sec fin
#plot_harmonique(acpf, 3)  # Humide début mais sec fin

```

ajouter sum montego aviso
```{r plot_indiv_propre}

plot_indiv <- function(acpf, type_rend, var, axe, variable){
  
  V <- paste0("V" ,axe)
  
  scores <- as.data.frame(acpf$scores)
  scores$exp <- noms
  scores <- scores |> 
    left_join(rendement |> 
                filter(type == type_rend,
                       variety == var))
  
  if(length(axe) == 2){
    
    scores |> 
      ggplot(aes(x = .data[[V[1]]], y = .data[[V[2]]])) +
      geom_point(aes(color = exp, size = value)) +
      geom_hline(yintercept = 0, color = "grey68", linewidth = 0.6) + 
      geom_vline(xintercept = 0, color = "grey68", linewidth = 0.6) +
      geom_text(aes(label = exp), vjust = -1) +
      theme_minimal() +
      scale_x_continuous(limits = c(-1000, 1000),breaks = seq(-1000, 1000, by = 200)) +
      scale_y_continuous(limits = c(-1000, 1000),breaks = seq(-1000, 1000, by = 200)) +
      guides(color="none",
             size=guide_legend(title=paste0(type_rend))) +
      theme(aspect.ratio = 1,
            plot.title = element_text(size = 18, face = "bold"),
            axis.title = element_text(size = 16),
            axis.text  = element_text(size = 14),
            legend.title = element_text(size = 13),
            legend.text  = element_text(size = 11))+
      labs(x = paste0("Dimension ", axe[1], " : ", round(acpf$varprop[axe[1]], 2)*100, "%"),
           y = paste0("Dimension ", axe[2], " : ", round(acpf$varprop[axe[2]], 2)*100, "%"),
           title = paste0("Le rendement ", type_rend, " sur le plan de l'ACP (axes ", axe[1], " et ", axe[2], ") avec la variable ", variable))
    
  }else if(length(axe) == 1){
    
    scores |> 
      ggplot(aes(x = .data[[V[1]]], y = 0)) +
      geom_point(aes(color = exp, size = value)) +
      geom_hline(yintercept = 0, color = "grey68", linewidth = 0.6) +
      geom_vline(xintercept = 0, color = "grey68", linewidth = 0.6) +
      geom_text(aes(label = exp), vjust = -1) +  # nom des sites au-dessus
      theme_minimal() +
      scale_x_continuous(limits = c(-1000, 1000),breaks = seq(-1000, 1000, by = 200)) +
      scale_y_continuous(limits = c(-1000, 1000),breaks = seq(-1000, 1000, by = 200)) +
      guides(color="none", size=guide_legend(title=paste0(type_rend))) +
      theme(aspect.ratio = 1,
            plot.title = element_text(size = 18, face = "bold"),
            axis.title = element_text(size = 16),
            axis.text  = element_text(size = 14),
            legend.title = element_text(size = 13),
            legend.text  = element_text(size = 11))+
      labs(x = paste0("Dimension ", axe[1], " : ", round(acpf$varprop[axe[1]], 2)*100, "%"),
           y = "",
           title = paste0("Le rendement ", type_rend, " sur l'axe de l'ACP (axe ", axe[1], ") avec la variable ", variable))
    
  }
}

fdobj <- data_acp_f(E.HYD_WSC, centre = F, plot = T)
acpf <- pca.fd(fdobj, nharm = 5) 
plot_indiv(acpf,type_rend = "SY", var = "Montego", axe = c(1, 2), "E.HYD_WSC" )


```

```{r}
plot_indiv <- function(acpf, type_rend = "SY", var = "Aviso", axe = c(1, 2), variable){
  
    V <- paste0("V" ,axe)
    
    scores <- as.data.frame(acpf$scores)
    scores$exp <- noms
    scores <- scores |> 
      left_join(rendement |> 
              filter(type == type_rend,
                     variety == var))
  
  if(length(axe) == 2){

    scores |> 
      ggplot(aes(x = .data[[V[1]]], y = .data[[V[2]]])) +
      geom_point(aes(color = exp, size = value)) +  
      geom_text(aes(label = exp), vjust = -1) +  # nom des sites au-dessus
      theme_minimal() +
      labs(x = paste0("Dimension ", axe[1], " : ", round(acpf$varprop[axe[1]], 2)*100, "%"),
           y = paste0("Dimension ", axe[2], " : ", round(acpf$varprop[axe[2]], 2)*100, "%"),
           title = paste0("Le rendement ", type_rend, " sur le plan de l'ACP (axes ", axe[1], " et ", axe[2], ") avec la variable ", as.character(variable)))
    
  }else if(length(axe) == 1){
    
        scores |> 
      ggplot(aes(x = .data[[V[1]]], y = 0)) +
      geom_point(aes(color = exp, size = value)) +  
      geom_text(aes(label = exp), vjust = -1) +  # nom des sites au-dessus
      theme_minimal() +
      labs(x = paste0("Dimension ", axe[1], " : ", round(acpf$varprop[axe[1]], 2)*100, "%"),
           y = "",
           title = paste0("Le rendement ", type_rend, " sur l'axe de l'ACP (axe ", axe[1], ") avec la variable ", as.character(variable)))
    
  }
}
```



```{r fun_acpf plot}
fun_acpf <- function(variable,
                     centre = F, plot = T, nbspines = 30,
                     nharm = 5){
  
  fdobj <- data_acp_f({{variable}}, centre = centre, plot = plot, nbspines = nbspines)  # crea data (spline)
  acpf <- pca.fd(fdobj, nharm = nharm)                          # pca fun
}

fun_acpf("TEMP_T_Q", nbspines = 10)
```


```{r fun_acpf plot}
fun_acpf_plot <- function(variable,
                          centre = F, plot = T, nbspines = 30,
                          nharm = 5,
                          type_rend = "SY", var = "Aviso", axe = c(1, 2)){
  
  fdobj <- data_acp_f({{variable}}, centre = centre, plot = plot, nbspines = nbspines)  # crea data (spline)
  acpf <- pca.fd(fdobj, nharm = nharm)                 # pca fun
  
  print("Le pourcentage d'explication de chaque axe de l'acpf est :")
  print(round(acpf$varprop, 3) * 100)
  
  # plot fonction moyenne
  plot(mean.fd(fdobj))
  
  plot_harmonique(acpf, 1)
  plot_harmonique(acpf, 2)
  plot_harmonique(acpf, 3)
  plot_harmonique(acpf, 4)
  plot_harmonique(acpf, 5)
  
  plot_indiv(acpf, type_rend = type_rend, var = var, axe = axe, variable={{variable}} ) 
  
}

fun_acpf_plot("TEMP_T_Q", nbspines = 20, axe = c(1, 3), type_rend = "SY")


```


```{r plot_fdobj_experience}
plot_fdobj_experience <- function(fdobj, experience){
  
  saison <- c("AUTOMNE", "HIVER", "MONTAISON", "FLORAISON", "P300-P1000")
  
  fd_subset <- fdobj[experience]
  
  n <- length(experience)
  cols <- viridis(n)
  
  par(mar = c(5, 4, 4, 8))
  
  plot(fd_subset,
       col = cols, 
       lty = 1, 
       xlab = "", 
       ylab = "Moyenne des températures",
       main = "Courbes fonctionnelles estimées", 
       xaxt = "n")
  
  colours <- adjustcolor(
    c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#F15854"),
    alpha.f = 0.25)
  
  yl <- par("usr")[3:4]
  
  rect(ref_lm_v[-length(ref_lm_v)],
       yl[1],
       ref_lm_v[-1],
       yl[2],
       col = colours,
       border = NA)
  
  y_text <- yl + 0.05 * diff(yl)
  
  x_centers <- (ref_lm_v[-length(ref_lm_v)] + ref_lm_v[-1]) / 2  # centre des rectangles
  y_label <- yl - 0.1 * diff(yl)            # un peu en dessous
  text(x = x_centers[1:length(saison)], 
       y = y_label, 
       labels = saison, 
       cex = 0.9, 
       xpd = TRUE)
  
  legend("topright", 
         legend = experience,
         col = cols,
         lty = 1,
         cex = 0.7,
         bty = "n",
         xpd = TRUE,
         inset = c(-0.2, 0), 
         seg.len = 1.5)
  
}

plot_fdobj_experience(fdobj, c("INRA13", "INRA18", "INRA12", "BGA11","BGA15")) 
```




```{r plot_courbe}

plot_courbe <- function(variable, normaliser = T, experience = NULL, centre = F, plot = T, nbspines = 30){
  
  if(variable == "TEMP_T_Q"){
    ylab <- "Température moyenne quotidienne"
  } else if (variable == "RAYO_SSI_Q"){
    ylab <- "Rayonnement quotidienne"
  } else if (variable == "E.HYD_WSC"){
    ylab <- "Teneur en eau quotidienne"
  }
  
  if(normaliser){
    fdobj <- data_acp_f({{variable}}, centre = centre, plot = plot, nbspines = nbspines)
    
    if(!is.null(experience)){fdobj <- fdobj[experience]}
    
    saison <- c("AUTOMNE", "HIVER", "MONTAISON", "FLORAISON", "P300-P1000")
    n <- length(experience)
    cols <- viridis(n)
    
    par(mar = c(5, 4, 4, 8))
    
    plot(fdobj,
         col = cols, 
         lty = 1, 
         xlab = "", 
         ylab = ylab,
         main = paste("Courbes fonctionnelles estimées :", expi), 
         xaxt = "n")
    
    colours <- adjustcolor(
      c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#F15854"),
      alpha.f = 0.25)
    
    yl <- par("usr")[3:4]
    
    rect(ref_lm_v[-length(ref_lm_v)],
         yl[1],
         ref_lm_v[-1],
         yl[2],
         col = colours,
         border = NA)
    
    y_text <- yl + 0.05 * diff(yl)
    
    x_centers <- (ref_lm_v[-length(ref_lm_v)] + ref_lm_v[-1]) / 2  # centre des rectangles
    y_label <- yl[1] - 0.1 * diff(yl)            # un peu en dessous
    text(x = x_centers[1:length(saison)], 
         y = y_label, 
         labels = saison, 
         cex = 0.9, 
         xpd = TRUE)
    
    legend("topright", 
           legend = experience,
           col = cols,
           lty = 1,
           cex = 0.7,
           bty = "n",
           xpd = TRUE,
           inset = c(-0.2, 0), 
           seg.len = 1.5)
  } else {
    
    dta <- meteo_brute |> 
      dplyr::select(exp, DATE_s, {{variable}}) |> 
      filter(is.null(experience) | exp %in% experience) |>
      mutate(DATE_s = as.numeric(as.Date(DATE_s)))
    
    if(is.null(experience)){experience <- unique(dta$exp)}
    
    for(expi in experience){
      print("a")
      png(filename = paste0("image/", variable, "_", expi, ".png"),
      width = 800, height = 600, res = 120)
      print("c")
      
      
      dta_i <- dta |> 
        filter(exp == expi,
               !is.na(DATE_s))
      
      rangeval <- c(min(dta_i$DATE_s), max(dta_i$DATE_s))
      print(expi)
      print(rangeval)
      basisobj <- create.bspline.basis(rangeval = rangeval, nbasis = nbspines)
      
      data_var <- dta_i |> 
        pivot_wider(names_from = DATE_s, values_from = {{variable}}) |> 
        column_to_rownames("exp") 
      data_var <- as.matrix(data_var) 
      
      time <- as.numeric(colnames(data_var))
      fdParobj <- fdPar(basisobj, lambda = 1e-3)
      
      fdsmooth <- smooth.basis(
        argvals  = time,
        y        = t(data_var),  # smooth.basis attend temps × individus
        fdParobj = fdParobj
      )
      
      
      fdobj <- fdsmooth$fd
      
      print("d")
      if(plot){
        
        saison <- c("AUTOMNE", "HIVER", "MONTAISON", "FLORAISON", "P300-P1000")
        n <- length(exp)
        cols <- viridis(n)
        
        par(mar = c(5, 4, 4, 8))
        
        plot(fdobj,
             lty = 1, 
             xlab = "", 
             ylab = ylab,
             main = paste("Courbes fonctionnelles estimées :", expi), 
             xaxt = "n"
             )
        
        colours <- adjustcolor(
          c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#F15854"),
          alpha.f = 0.25)
        
        yl <- par("usr")[3:4]
        
        print("e")
        
        lm_v <- lm |> 
          filter(PARTENAIRE == "INRA11") |> 
          dplyr::select(DEBUT_EXP_s, DEBUT_CW_s, FIN_CW_s, DEBUT_FLO_s, FIN_FLO_s, FIN_EXP_s ) |> 
          as.vector() |> 
          unlist() |> 
          as.Date() |> 
          as.numeric()
        
        rect(lm_v[-length(lm_v)],
             yl[1],
             lm_v[-1],
             yl[2],
             col = colours,
             border = NA)
        
        y_text <- yl + 0.05 * diff(yl)
        
        x_centers <- (lm_v[-length(lm_v)] + lm_v[-1]) / 2  # centre des rectangles
        y_label <- yl[1] - 0.1 * diff(yl)            # un peu en dessous
        text(x = x_centers[1:length(saison)], 
             y = y_label, 
             labels = saison, 
             cex = 0.9, 
             xpd = TRUE)
        
        legend("topright", 
               legend = exp,
               col = cols,
               lty = 1,
               cex = 0.7,
               bty = "n",
               xpd = TRUE,
               inset = c(-0.2, 0), 
               seg.len = 1.5)
        print("f")
        
      }
      print("b")
      dev.off()
    }
    
  }
  
}


```

