---
title: "meteo"
format: html
---


Librairies
```{r}
library(tidyverse)
library(readxl)
library(lubridate)
library(FactoMineR)
```


Regarder la météo
```{r}

read_meteo <- function(link){
  data <- read_excel(link, col_names = FALSE) |> 
    mutate_all(as.character) |> 
    as.data.frame()
  
  
  data <- data[-dim(data)[1], ]
  ph <- which(data[4, ] == "Photoperiode")
  data <- data[, -((ph + 1): dim(data)[2])]
  
  iT <- which(data[1, ] == "TEMPERATURE")
  iEH <- which(data[1, ] == "ETAT HYDRIQUE")
  iR <- which(data[1, ] == "RAYONNEMENT")
  iF <- length(data[1, ])
  iL <- c(rep("", iT-1), rep("TEMP_", iEH - iT), rep("E.HYD_", iR - iEH), rep("RAYO_", iF - iR), "")
  
  colnames(data) <- as.character(paste0(iL, as.vector(data[4, ])))
  
  data <- data[-c(1:4), ]
  
  data <- data[!is.na(data[[7]]), ]
  
  data <- data |> 
    filter(! is.na(DATE))
  
  data <- data[, -c(1:2)]  # 2 ->3
  
  data <- data |> mutate_all(as.numeric)
  data <- data |> mutate(DATE = as_date(DATE, origin = "1899-12-30"))
}

```




```{r}
INRA11 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.1_R2011/191118_INRA11_LR_IPC_Calcul_ok.xlsx")
BGA11 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.1_R2011/191119_BGA11_MD11_IPC_Calcul_ok.xlsx")

INRA12 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.2_R2012/191118_INRA12_LR_IPC_Calcul_ok.xlsx")

INRA13 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.3_R2013/191118_INRA13_LR_IPC_Calcul_ok.xlsx")
TI13 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.3_R2013/191119_TI13_DIJ13_IPC_Calcul_ok.xlsx")

EUR14 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.4_R2014/191018_EUR14_IPC_Calcul_ok.xlsx")
RAGT14 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.4_R2014/191022_RAGT14_IPC_Calcul_ok.xlsx")
MAD14 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.4_R2014/191106_MAD14_IPC_Calcul_ok.xlsx")
SYN14 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.4_R2014/191106_SYN14_IPC_Calcul_ok.xlsx")



TI15 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.5_R2015/191018_TI15_IPC_Calcul_ok.xlsx")
LIM15 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.5_R2015/191022_LIM15_IPC_Calcul_ok.xlsx")
SYN15 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.5_R2015/191022_SYN15_IPC_Calcul_ok.xlsx")
INRA15 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.5_R2015/191022_INRA15_IPC_Calcul_ok.xlsx")
BGA15 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.5_R2015/191018_BGA15_IPC_Calcul_ok.xlsx")
RAGT15 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.5_R2015/191106_RAGT15_IPC_Calcul_ok.xlsx")
MAD15 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.5_R2015/191106_MAD15_IPC_Calcul_ok.xlsx")

INRA16 <- read_meteo("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.6_R2016/191025_INRA16_IPC_Calcul_ok.xlsx")

INRA17 <- read_xlsx("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.7_R2017/191114_INRA17_LR_IPC_Calcul_ok.xlsx")

INRA18 <- read_xlsx("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.8_R2018/191118_INRA18_LR_IPC_Calcul_ok.xlsx")
EUR18 <- read_xlsx("data/climate_data/indicateurs_journaliers_par_essais/1.1.4.2.8_R2018/191031_EUR18_BLO_IPC_Calcul_ok.xlsx")

dts <- list(
  INRA11 = INRA11,
  BGA11 = BGA11,
  INRA12 = INRA12,
  INRA13 = INRA13,
  TI13 = TI13,
  EUR14 = EUR14,
  SYN14 = SYN14,
  MAD14 = MAD14,
  RAGT14 = RAGT14,
  TI15 = TI15,
  LIM15 = LIM15,
  SYN15 = SYN15,
  INRA15 = INRA15,
  BGA15 = BGA15,
  RAGT15 = RAGT15,
  MAD15 = MAD15,
  INRA16 = INRA16, 
  INRA17 = INRA17,
  INRA18 = INRA18,
  EUR18 = EUR18
)

dt_meteo <- imap_dfr(dts, ~ mutate(exp = .y, .x))
names(dt)

rm(INRA11,BGA11,INRA12,INRA13,TI13,EUR14,SYN14,MAD14,RAGT14,TI15,LIM15,SYN15,INRA15,BGA15,RAGT15,MAD15,INRA16,INRA17,INRA18,EUR18)

```



# Visualisation Météo

```{r}

graph_TEMP_T_Q <- dt_meteo  |> 
  mutate(
    m = month(DATE),
    d = day(DATE),
    fake_year = if_else(
      (m > 8) | (m == 8 & d >= 15), 2000, 2001),
    date_no_year = as.Date(sprintf("%04d-%02d-%02d", fake_year, m, d))) |> 
  ggplot(aes(x = date_no_year, y = TEMP_T_Q, color = exp, group = exp)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Date (sans année)", y = "Valeur") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(
    date_labels = "%d-%b",
    limits = as.Date(c("2000-08-15", "2001-08-15"))
  )

graph_E.HYD_PRELIQ <- dt_meteo  |> 
  mutate(
    m = month(DATE),
    d = day(DATE),
    fake_year = if_else(
      (m > 8) | (m == 8 & d >= 15), 2000, 2001),
    date_no_year = as.Date(sprintf("%04d-%02d-%02d", fake_year, m, d))) |> 
  ggplot(aes(x = date_no_year, y = E.HYD_PRELIQ_Q, color = exp, group = exp)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Date (sans année)", y = "Valeur") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(
    date_labels = "%d-%b",
    limits = as.Date(c("2000-08-15", "2001-08-15"))
  )

graph_E.HYD_CUMMUL_P <- dt_meteo  |> 
  mutate(
    m = month(DATE),
    d = day(DATE),
    fake_year = if_else(
      (m > 8) | (m == 8 & d >= 15), 2000, 2001),
    date_no_year = as.Date(sprintf("%04d-%02d-%02d", fake_year, m, d))) |> 
  ggplot(aes(x = date_no_year, y = E.HYD_PRELIQ_Q, color = exp, group = exp)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Date (sans année)", y = "Valeur") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(
    date_labels = "%d-%b",
    limits = as.Date(c("2000-08-15", "2001-08-15"))
  )

graph_E.HYD_ETAT <- dt_meteo  |> 
  mutate(
    m = month(DATE),
    d = day(DATE),
    fake_year = if_else(
      (m > 8) | (m == 8 & d >= 15), 2000, 2001),
    date_no_year = as.Date(sprintf("%04d-%02d-%02d", fake_year, m, d))) |> 
  ggplot(aes(x = date_no_year, y = `E.HYD_ETAT RU_1`, color = exp, group = exp)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Date (sans année)", y = "Valeur") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(
    date_labels = "%d-%b",
    limits = as.Date(c("2000-08-15", "2001-08-15"))
  )

graph_RAYO <- dt_meteo  |> 
  mutate(
    m = month(DATE),
    d = day(DATE),
    fake_year = if_else(
      (m > 8) | (m == 8 & d >= 15), 2000, 2001),
    date_no_year = as.Date(sprintf("%04d-%02d-%02d", fake_year, m, d))) |> 
  ggplot(aes(x = date_no_year, y = RAYO_SSI_Q, color = exp, group = exp)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Date (sans année)", y = "Valeur") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(
    date_labels = "%d-%b",
    limits = as.Date(c("2000-08-15", "2001-08-15"))
  )

graph_Photoper <- dt_meteo  |> 
  mutate(
    m = month(DATE),
    d = day(DATE),
    fake_year = if_else(
      (m > 8) | (m == 8 & d >= 15), 2000, 2001),
    date_no_year = as.Date(sprintf("%04d-%02d-%02d", fake_year, m, d))) |> 
  ggplot(aes(x = date_no_year, y = Photoperiode, color = exp, group = exp)) +
  geom_line() +
  theme_minimal() +
  labs(x = "Date (sans année)", y = "Valeur") +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  scale_x_date(
    date_labels = "%d-%b",
    limits = as.Date(c("2000-08-15", "2001-08-15"))
  )

graph_TEMP_T_Q
graph_E.HYD_PRELIQ
graph_E.HYD_CUMMUL_P
graph_E.HYD_ETAT
graph_RAYO
graph_Photoper


```



# lecture landmarks

```{r}

landmarks <- read_excel("data/Date_landmarks_20essais.xlsx") |> 
  mutate(DEBUT_EXP = as.Date(DEBUT_EXP),
         DEBUT_CW = as.Date(DEBUT_CW),
         FIN_CW = as.Date(FIN_CW),
         DEBUT_FLO = as.Date(DEBUT_FLO),
         FIN_FLO = as.Date(FIN_FLO),
         FIN_EXP = as.Date(FIN_EXP))


summary(landmarks)

```


Durée de chaque période
```{r}

landmarks |> 
  select(YEAR, ENVIRONNEMENT, DUREE_AU, DUREE_CW, DUREE_BO, DUREE_FLO, DUREE_P) |> 
  pivot_longer(c(DUREE_AU, DUREE_CW, DUREE_BO, DUREE_FLO, DUREE_P), names_to = "DUREE") |> 
  ggplot(aes(x = YEAR, y = value, colour = ENVIRONNEMENT)) +
  geom_point() +
  facet_wrap(~DUREE) +
  theme_minimal()

```
La floraison dure trois semaines
A mettre dans l'ordre des saisons


# landmark

```{r}










landmarks |> 
  mutate(
    m_e = month(DEBUT_EXP),
    d_e = day(DEBUT_EXP),
    fake_year_e = if_else((m_e > 8) | (m_e == 8 & d_e >= 15), 2000, 2001),
    DEBUT_EXP = as.Date(sprintf("%04d-%02d-%02d", fake_year_e, m_e, d_e)),
    
    m_d = month(DEBUT_CW),
    d_d = day(DEBUT_CW),
    fake_year_d = if_else((m_d > 8) | (m_d == 8 & d_d >= 15), 2000, 2001),
    DEBUT_CW = as.Date(sprintf("%04d-%02d-%02d", fake_year_d, m_d, d_d)),

    m_f = month(FIN_CW),
    d_f = day(FIN_CW),
    fake_year_f = if_else((m_f > 8) | (m_f == 8 & d_f >= 15), 2000, 2001),
    FIN_CW = as.Date(sprintf("%04d-%02d-%02d", fake_year_f, m_f, d_f)),

    m_flo = month(DEBUT_FLO),
    d_flo = day(DEBUT_FLO),
    fake_year_flo = if_else((m_flo > 8) | (m_flo == 8 & d_flo >= 15), 2000, 2001),
    DEBUT_FLO = as.Date(sprintf("%04d-%02d-%02d", fake_year_flo, m_flo, d_flo)),

    m_ff = month(FIN_FLO),
    d_ff = day(FIN_FLO),
    fake_year_ff = if_else((m_ff > 8) | (m_ff == 8 & d_ff >= 15), 2000, 2001),
    FIN_FLO = as.Date(sprintf("%04d-%02d-%02d", fake_year_ff, m_ff, d_ff)),

    m_fe = month(FIN_EXP),
    d_fe = day(FIN_EXP),
    fake_year_fe = if_else((m_fe > 8) | (m_fe == 8 & d_fe >= 15), 2000, 2001),
    FIN_EXP = as.Date(sprintf("%04d-%02d-%02d", fake_year_fe, m_fe, d_fe)),
  ) |> 
  select(YEAR, ENVIRONNEMENT, DEBUT_EXP, DEBUT_CW, FIN_CW, DEBUT_FLO, FIN_FLO, FIN_EXP) |> 
  pivot_longer(c(DEBUT_EXP, DEBUT_CW, FIN_CW, DEBUT_FLO, FIN_FLO, FIN_EXP),
               names_to = "type_date",
               values_to = "value") |>  
  mutate(
    type_date = factor(type_date, levels = c("DEBUT_EXP", "DEBUT_CW", "FIN_CW", "DEBUT_FLO", "FIN_FLO", "FIN_EXP")))|>

  ggplot(aes(x = type_date, y = value)) +
  geom_boxplot(outlier.shape = NA) +      
  geom_point(aes(colour = ENVIRONNEMENT), alpha = 0.6) + 
  geom_line(
    aes(group = ENVIRONNEMENT, colour = ENVIRONNEMENT), alpha = 0.6
  ) +
  theme_minimal()

```


```{r}
landmarks |> ggplot(aes(x = as.factor(YEAR), y = DUREE_AU)) + geom_boxplot()
landmarks |> ggplot(aes(x = as.factor(YEAR), y = DUREE_CW)) + geom_boxplot()
landmarks |> ggplot(aes(x = as.factor(YEAR), y = DUREE_BO)) + geom_boxplot()
landmarks |> ggplot(aes(x = as.factor(YEAR), y = DUREE_FLO)) + geom_boxplot()
landmarks |> ggplot(aes(x = as.factor(YEAR), y = DUREE_P)) + geom_boxplot()
```


```{r}


l <- l |> 
  mutate(DEBUT_CW_n = as.numeric(DEBUT_CW),
         FIN_CW_n = as.numeric(FIN_CW),
         FLORAISON_n = as.numeric(FLORAISON))



```








```{r}

debut_exp <- c()
for (dt in dts) {
  debut_exp <- c(debut_exp, dt$DATE[1])
}

l <- landmarks |> 
  mutate(FIN_FLO = as.Date(FLORAISON)+21) |> 
  mutate(DEBUT_EXP = as.Date(debut_exp))


library(writexl)

#write_xlsx(l, "data/Date_landmarks_20essais.xlsx")


```




