---
title: "Nuage"
format: html
---

#Importer ACP.f

```{r}
dt_meteo <- read.csv("data/meteo_lm")
```


```{r}
chrono_exp <- function(data, var, exp_sel = NULL) {

  if (!inherits(data$DATE_s, "Date")) {
    data$DATE_s <- as.Date(data$DATE_s)
  }

  if (!is.null(exp_sel)) {
    data <- dplyr::filter(data, exp %in% exp_sel)
  }

  ggplot(data, aes(x = DATE_s, y = .data[[var]], color = exp, group = exp)) +
    geom_line() +
    theme_minimal() +
    labs(x = "Date", y = var) +
    theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
    scale_x_date(
      date_labels = "%d-%b",
      limits = as.Date(c("2000-08-15", "2001-08-15"))
    )
}

```



TEMP_T_Q

```{r}
fdobj <- data_acp_f(TEMP_T_Q, centre = F, plot = T)
pca <- pca.fd(fdobj, nharm = 5)
plot_indiv(pca,
           type_rend = "SY",
           var = "Montego",
           axe = c(1, 3),
           variable = "TEMP_T_Q")
chrono_exp(dt_meteo, "TEMP_T_Q", exp_sel = c("INRA13", "INRA18"))


plot(fdobj[c("INRA13", "BGA11")]) #première comp
plot(fdobj[c("TI13", "EUR14")])   #deuxième comp
plot(fdobj[c("INRA13", "TI13")])   # troisième comp


```

```{r}
#library(viridis)


plot_fdobj_experience <- function(fdobj, experience){
  
  saison <- c("AUTOMNE", "HIVER", "MONTAISON", "FLORAISON", "P300-P1000")
  
  fd_subset <- fdobj[experience]
  
  n <- length(experience)
  cols <- viridis(n)
  
  par(mar = c(5, 4, 4, 8))
  
  plot(fd_subset,
       col = cols, 
       lty = 1, 
       xlab = "", 
       ylab = "Moyenne des températures",
       main = "Courbes fonctionnelles estimées", 
       xaxt = "n")
  
  colours <- adjustcolor(
  c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#F15854"),
  alpha.f = 0.25)
  
  yl <- par("usr")[3:4]

  rect(ref_lm_v[-length(ref_lm_v)],
     yl[1],
     ref_lm_v[-1],
     yl[2],
     col = colours,
     border = NA)
  
  y_text <- yl + 0.05 * diff(yl)
  
  x_centers <- (ref_lm_v[-length(ref_lm_v)] + ref_lm_v[-1]) / 2  # centre des rectangles
  y_label <- yl - 0.1 * diff(yl)                         # un peu en dessous
  text(x = x_centers[1:length(saison)], 
       y = y_label, 
       labels = saison, 
       cex = 0.9, 
       xpd = TRUE)
  
  legend("topright", 
       legend = experience,
       col = cols,
       lty = 1,
       cex = 0.7,
       bty = "n",
       xpd = TRUE,
       inset = c(-0.2, 0), 
       seg.len = 1.5)

}

plot_fdobj_experience(fdobj, c("INRA13", "INRA18", "INRA12", "BGA11","BGA15")) 

```

Faire appel aux landmarks de exp spécifiquement 
ref_lm + rect
