---
title: "reg_acpf"
format: html
---

```{r library}

library(tidyverse)
library(FactoMineR)
library(Factoshiny)
library(pls)
library(fda)
conflicted::conflicts_prefer(dplyr::filter, dplyr::select)



```


```{r noms}
noms <- c("INRA11","BGA11",
          "INRA12",
          "INRA13","TI13",
          "EUR14","SYN14","MAD14","RAGT14",
          "TI15","LIM15","SYN15","INRA15","BGA15","RAGT15","MAD15",
          "INRA16",
          "INRA17",
          "INRA18","EUR18")
```


```{r data}
meteo_lm <- read.csv("data/meteo_lm")
summary(meteo_lm)
glimpse(meteo_lm)

rendement <- read.csv("data/rendement.csv") |>
  filter(type == "SY",
         !is.na(value)) |>
  mutate(variety = sub("^[^_]*_[^_]*_", "", variety)) |> 
  select(exp, type, value, variety)

info <- read.csv("data/dt_anova") |> 
  rename(exp = PARTENAIRE) |> 
  select(exp, Year, Latitude, Longitude, AN, ADB, NNI, Ntotal, WSC_MAX, WSC_I, DBI, DAI, RO, RF)

landmark <- read.csv("data/landmarks.csv") |> 
  rename(exp = PARTENAIRE) |> 
  select(exp, DUREE_AU, DUREE_CW, DUREE_BO, DUREE_FLO, DUREE_P) # attention à duree flo

dta <- rendement |> 
  left_join(info) |> 
  left_join(landmark) |> 
  arrange(match(exp, noms)) |> 
  filter(!is.na(Year)) |> 
  mutate(variety = as.factor(variety),
         Year = as.factor(Year))

ref_lm <- read.csv("data/ref_lm.csv")
ref_lm_v <- ref_lm$x[2:7]

rm(rendement, info, landmark, ref_lm)

```


```{r fonction crea data pour acp f}

data_acp_f <- function(var, centre = F, plot = T, nbspines = 30){
  rangeval <- c(min(meteo_lm$date_ref), max(meteo_lm$date_ref)) # définition de l'échelle (les longueurs d'ondes)
  nbasis <- nbspines # Nombre de splines utilisées
  basisobj <- create.bspline.basis(rangeval = rangeval, nbasis = nbasis) # création d'une base d'objet
  
  
  data_var <- meteo_lm |> 
    dplyr::select(exp, date_ref, {{var}}) |> 
    mutate(date_ref = as.numeric(date_ref)) |> 
    pivot_wider(names_from = date_ref, values_from = {{var}}) |> 
    column_to_rownames("exp") 
  
  
  ##### si on veut faire une acp et non une svd 
  if(centre){
    m <- apply(data_var, 1, mean)
    s <- apply(data_var - m, 1, sd)
    
    data_var <- (data_var - m) / s |> 
      as.matrix() 
  }
  
  data_var <- as.matrix(data_var) 
  
  time <- as.numeric(colnames(data_var))
  fdParobj <- fdPar(basisobj, lambda = 1e-3)
  
  fdsmooth <- smooth.basis(
    argvals  = time,
    y        = t(data_var),  # smooth.basis attend temps × individus
    fdParobj = fdParobj
  )
  
  
  fdobj <- fdsmooth$fd
  
  if(plot){plot(fdobj)}
  
  return(fdobj)
}

```

```{r}


acpf_HYD <- pca.fd(data_acp_f(E.HYD_WSC, centre = F, plot = F, nbspines = 15), nharm = 5)
acpf_TEMP <- pca.fd(data_acp_f(TEMP_T_Q, centre = F, plot = F, nbspines = 10), nharm = 5)
acpf_RAYO <- pca.fd(data_acp_f(RAYO_SSI_Q, centre = F, plot = F, nbspines = 20), nharm = 5)
colnames(acpf_HYD$scores) <- c("PC1_HYD", "PC2_HYD", "PC3_HYD", "PC4_HYD" ,"PC5_HYD")
colnames(acpf_TEMP$scores) <- c("PC1_TEMP", "PC2_TEMP", "PC3_TEMP", "PC4_TEMP" ,"PC5_TEMP")
colnames(acpf_RAYO$scores) <- c("PC1_RAYO", "PC2_RAYO", "PC3_RAYO", "PC4_RAYO" ,"PC5_RAYO")


dta_acpf <- dta |> 
  left_join(acpf_HYD$scores |> cbind(data.frame(exp = noms))) |>
  left_join(acpf_TEMP$scores |> cbind(data.frame(exp = noms))) |> 
  left_join(acpf_RAYO$scores |> cbind(data.frame(exp = noms))) |>
  select(-DUREE_FLO)

summary(dta_acpf)





```



```{r}



mod <- plsr(
  value ~ .,
  data = dta_acpf[, c(3, 6:36)],
  scale = TRUE,
  validation = "LOO",   # robuste avec petit n
  ncomp = 20            # max raisonnable
)

rmsep_mod <- RMSEP(mod)
plot(rmsep_mod, legendpos = "topright")

rmsep <- rmsep_mod$val["CV", , -1]  # enlève l'intercept
opt_ncomp <- which.min(rmsep)

opt_ncomp

min(rmsep)

coef_pls <- coef(mod, ncomp = opt_ncomp)

coef_df <- data.frame(
  variable = rownames(coef_pls),
  coefficient = as.vector(coef_pls)
)

ggplot(coef_df, aes(x = reorder(variable, coefficient), y = coefficient)) +
  geom_col(fill = "steelblue") +
  coord_flip() +
  labs(title = paste0("Coefficients PLS (",
                      opt_ncomp, " composantes) : RMSEP = ",
                      round(min(rmsep), 2)),
       x = "Variable",
       y = "Coefficient") +
  theme_classic()


```






```{r}
grid <- expand.grid(
  nb_HYD  = 5:25,
  nb_RAYO = 15:25
)
run_benchmark <- function(nb_HYD, nb_RAYO) {
  
  # ACP fonctionnelles
  acpf_HYD <- pca.fd(
    data_acp_f(E.HYD_WSC, centre = FALSE, plot = FALSE, nbspines = nb_HYD),
    nharm = 5
  )
  
  acpf_TEMP <- pca.fd(
    data_acp_f(TEMP_T_Q, centre = FALSE, plot = FALSE, nbspines = 10),
    nharm = 5
  )
  
  acpf_RAYO <- pca.fd(
    data_acp_f(RAYO_SSI_Q, centre = FALSE, plot = FALSE, nbspines = nb_RAYO),
    nharm = 5
  )
  
  
  scores_HYD <- as.data.frame(acpf_HYD$scores)
  scores_HYD$exp <- noms
  
  scores_TEMP <- as.data.frame(acpf_TEMP$scores)
  scores_TEMP$exp <- noms
  
  scores_RAYO <- as.data.frame(acpf_RAYO$scores)
  scores_RAYO$exp <- noms
  
  # Dataset PLS
  dta_tmp <- dta |>
    left_join(scores_HYD,  by = "exp") |>
    left_join(scores_TEMP, by = "exp") |>
    left_join(scores_RAYO, by = "exp") |>
    select(-DUREE_FLO)
  
  # PLS
  mod <- plsr(
    value ~ .,
    data = dta_tmp[, c(3, 6:ncol(dta_tmp))],
    scale = TRUE,
    validation = "LOO",
    ncomp = 20
  )
  
  rmsep <- RMSEP(mod)$val["CV", , -1]
  min_rmsep <- min(rmsep, na.rm = TRUE)
  opt_ncomp <- which.min(rmsep)
  
  return(
    data.frame(
      nb_HYD     = nb_HYD,
      nb_RAYO    = nb_RAYO,
      RMSEP_min  = min_rmsep,
      ncomp_opt  = opt_ncomp
    )
  )
}


results <- do.call(
  rbind,
  apply(grid, 1, function(x)
    run_benchmark(x["nb_HYD"], x["nb_RAYO"]))
)

best <- results[which.min(results$RMSEP_min), ]
best

ggplot(results, aes(nb_HYD, nb_RAYO, fill = RMSEP_min)) +
  geom_tile() +
  scale_fill_viridis_c() +
  labs(
    title = "Benchmark du nombre de splines (TEMP fixé à 10)",
    x = "Nb splines HYD",
    y = "Nb splines RAYO",
    fill = "RMSEP (LOO)"
  ) +
  theme_minimal()
```



```{r}

cor <- cor(dta[, c(3, 6:36)])
corrplot::corrplot(cor)
#value*PC3_RAYO = -0.53
#value*PC4_HYD = -0.38
#value*PC3_TEMP = -0.36
#value*PC4_RAYO = -0.08
#value*PC1_HYD  = -0.004
```



```{r}






t <- 11219:11502
sign_TEMP_acp <- numeric(length(t))

for (i in seq_len(5)) {
  
  coef_i <- coef_df |>
    filter(variable == paste0("PC", i, "_TEMP")) |>
    pull(coefficient)
  
  sign_TEMP_acp <- sign_TEMP_acp +
    coef_i * eval.fd(t, acpf_TEMP$harmonics[i])
}


png(filename = paste0("image/reg_fun/sing_asso_TEMP_norm.png"), 
    width = 1800, height = 900, res = 180)

ylim <- par("usr")[3:4]
num <- c("Première", "Deuxième", "Troisième", "Quatrième", "Cinquième")
saison <- c("AUTOMNE", "HIVER", "MONTAISON", "FLORAISON", "P300-P1000")


plot(t, sign_TEMP_acp,
     type = "l",
     xlab = "", ylab = "sign_TEMP_acp",
     main = "sign asso TEMP norm")


cols <- adjustcolor(
  c("#E69F00", "#56B4E9", "#009E73", "#F0E442", "#F15854"),
  alpha.f = 0.25)

rect(ref_lm_v[-length(ref_lm_v)],  # xleft
     ylim[1],                # ybottom
     ref_lm_v[-1],               # xright
     ylim[2],                # ytop
     col = cols,
     border = NA)

y_text <- ylim[1] + 0.05 * diff(ylim)

x_centers <- (ref_lm_v[-length(ref_lm_v)] + ref_lm_v[-1]) / 2  # centre des rectangles
y_label <- ylim[1] - 0.1 * diff(ylim)                         # un peu en dessous
text(x = x_centers[1:length(saison)], 
     y = y_label, 
     labels = saison, 
     cex = 0.9, 
     xpd = TRUE)
dev.off()

```

